apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xeks.k8s.demo.upbound.io
  labels:
    cloud: aws
spec:
  compositeTypeRef:
    apiVersion: demo.upbound.io/v1alpha1
    kind: XK8s
  patchSets: []
  resources: []