- op: add
  path: /spec/resources/-
  value:
    name: clusterSecurityGroup
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: SecurityGroup
      spec:
        forProvider:
          description: "Cluster communication with worker nodes"
          #vpcIdSelector:
          #  matchControllerRef: true
    patches:
      - fromFieldPath: spec.vpcId
        toFieldPath: spec.forProvider.vpcId
      - fromFieldPath: spec.region
        toFieldPath: spec.forProvider.region
      - type: PatchSet
        patchSetName: standardTags
      - type: PatchSet
        patchSetName: network-id
      - fromFieldPath: spec.id
        toFieldPath: metadata.name
        transforms:
        - type: string
          string:
            fmt: "%s-eskcluster-sg"
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.name
        transforms:
        - type: string
          string:
            fmt: "%s-eskcluster-sg"
      - fromFieldPath: spec.id
        toFieldPath: metadata.labels[securitygroup]
        transforms:
        - type: string
          string:
            fmt: "%s-eskcluster-sg"
      
## SecurityGroupRule for Cluster Ingress
- op: add
  path: /spec/resources/-
  value:
    name: clusterSecurityGroupRuleIngress
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: SecurityGroupRule
      spec:
        forProvider:
          description: "Allow pods to communicate with the cluster API Server -"
          fromPort: 443
          protocol: "tcp"
          toPort: 443
          type: ingress
          securityGroupIdSelector:
            matchControllerRef: true
          sourceSecurityGroupIdSelector:
            matchControllerRef: true
    patches:
      - fromFieldPath: spec.region
        toFieldPath: spec.forProvider.region
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.securityGroupIdSelector.matchLabels[securitygroup]
        transforms:
        - type: string
          string:
            fmt: "%s-eskcluster-sg"
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.sourceSecurityGroupIdSelector.matchLabels[securitygroup]
        transforms:
        - type: string
          string:
            fmt: "%s-node-sg"
      - fromFieldPath: spec.id
        toFieldPath: metadata.name
        transforms:
        - type: string
          string:
            fmt: "%s-sg-rule-pods-to-api-server"
    ## SecurityGroupRule for Cluster Egress
- op: add
  path: /spec/resources/-
  value:
    name: clusterSecurityGroupRuleEgress
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: SecurityGroupRule
      spec:
        forProvider:
          description: "Egress"
          fromPort: 0
          protocol: "-1"
          toPort: 0
          type: egress
          cidrBlocks:
            - "0.0.0.0/0"
          securityGroupIdSelector:
            matchControllerRef: true
    patches:
      - fromFieldPath: spec.region
        toFieldPath: spec.forProvider.region
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.securityGroupIdSelector.matchLabels[securitygroup]
        transforms:
        - type: string
          string:
            fmt: "%s-eskcluster-sg"
      - fromFieldPath: spec.id
        toFieldPath: metadata.name
        transforms:
        - type: string
          string:
            fmt: "%s-sg-rule-cluster-egress"