- op: add
  path: /spec/resources/-
  value:
    name: gateway
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: InternetGateway
      spec:
        forProvider:
          #vpcIdSelector:
          #  matchControllerRef: true
    patches:
      - fromFieldPath: spec.vpcId
        toFieldPath: spec.forProvider.vpcId
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.Name
        transforms:
        - type: string
          string:
            fmt: "%s-ig"
      - fromFieldPath: spec.region
        toFieldPath: spec.forProvider.region
      - type: PatchSet
        patchSetName: network-id