- op: add
  path: /spec/resources/-
  value:
    name: nodeSecurityGroup
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: SecurityGroup
      spec:
        forProvider:
          description: "Security group for all nodes in the cluster"
          #vpcIdSelector:
          #  matchControllerRef: true
    patches:
      - fromFieldPath: spec.vpcId
        toFieldPath: spec.forProvider.vpcId
      - fromFieldPath: spec.region
        toFieldPath: spec.forProvider.region
      - type: PatchSet
        patchSetName: standardTags
      - type: PatchSet
        patchSetName: network-id
      - fromFieldPath: spec.id
        toFieldPath: metadata.name
        transforms:
        - type: string
          string:
            fmt: "%s-node-sg"
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.name
        transforms:
        - type: string
          string:
            fmt: "%s-node-sg"
      - fromFieldPath: spec.id
        toFieldPath: metadata.labels[securitygroup]
        transforms:
        - type: string
          string:
            fmt: "%s-node-sg"
- op: add
  path: /spec/resources/-
  value:
    name: nodeSecurityGroupRuleEgress
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: SecurityGroupRule
      spec:
        forProvider:
          description: "Allow egress from the nodes"
          fromPort: 0
          protocol: "-1"
          toPort: 0
          cidrBlocks:
            - "0.0.0.0/0"
          type: egress
          securityGroupIdSelector:
            matchControllerRef: true
    patches:
      - fromFieldPath: spec.region
        toFieldPath: spec.forProvider.region
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.securityGroupIdSelector.matchLabels[securitygroup]
        transforms:
        - type: string
          string:
            fmt: "%s-node-sg"
      - fromFieldPath: spec.id
        toFieldPath: metadata.name
        transforms:
        - type: string
          string:
            fmt: "%s-sg-rule-node-egress"
- op: add
  path: /spec/resources/-
  value:
    name: nodeSecurityGroupRuleDemoIngressSelf
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: SecurityGroupRule
      spec:
        forProvider:
          description: "Allow node to communicate with each other"
          fromPort: 0
          protocol: "-1"
          toPort: 65535
          type: ingress
          securityGroupIdSelector:
            matchControllerRef: true
          sourceSecurityGroupIdSelector:
            matchControllerRef: true
    patches:
      - fromFieldPath: spec.region
        toFieldPath: spec.forProvider.region
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.securityGroupIdSelector.matchLabels[securitygroup]
        transforms:
        - type: string
          string:
            fmt: "%s-node-sg"
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.sourceSecurityGroupIdSelector.matchLabels[securitygroup]
        transforms:
        - type: string
          string:
            fmt: "%s-node-sg"
      - fromFieldPath: spec.id
        toFieldPath: metadata.name
        transforms:
        - type: string
          string:
            fmt: "%s-sg-rule-node-to-node"
- op: add
  path: /spec/resources/-
  value:
    name: nodeSecurityGroupRuleDemoIngressCluster
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: SecurityGroupRule
      spec:
        forProvider:
          description: "Allow worker Kubelets and pods to receive communication from the cluster control plane"
          fromPort: 1025
          protocol: "tcp"
          toPort: 65535
          type: ingress
          securityGroupIdSelector:
            matchControllerRef: true
          sourceSecurityGroupIdSelector:
            matchControllerRef: true
    patches:
      - fromFieldPath: spec.region
        toFieldPath: spec.forProvider.region
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.securityGroupIdSelector.matchLabels[securitygroup]
        transforms:
        - type: string
          string:
            fmt: "%s-node-sg"
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.sourceSecurityGroupIdSelector.matchLabels[securitygroup]
        transforms:
        - type: string
          string:
            fmt: "%s-node-sg"
      - fromFieldPath: spec.id
        toFieldPath: metadata.name
        transforms:
        - type: string
          string:
            fmt: "%s-sg-rule-kubelets"