- op: add
  path: /spec/resources/-
  value:
    name: nodeGroupPublic
    base:
      apiVersion: eks.aws.upbound.io/v1beta1
      kind: NodeGroup
      spec:
        forProvider:
          clusterNameSelector:
            matchControllerRef: true
          nodeRoleArnSelector:
            matchControllerRef: true
          subnetIdSelector:
            matchLabels:
              access: public
          scalingConfig:
            - desiredSize: 3
              minSize: 3
              maxSize: 5
          launchTemplate:
            - version: "1"
    patches:
      - fromFieldPath: spec.k8Version
        toFieldPath: spec.forProvider.version
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.launchTemplate[0].name
        transforms:
          - type: string
            string:
              fmt: "%s-lt"
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.nodeRoleArnSelector.matchLabels[role]
        transforms:
          - type: string
            string:
              fmt: "%s-nodegroup"
      - fromFieldPath: spec.region
        toFieldPath: spec.forProvider.region
      - fromFieldPath: "spec.id"
        toFieldPath: spec.forProvider.subnetSelector.matchLabels[networks.aws.platformref.crossplane.io/network-id]