- op: add
  path: /spec/resources/-
  value:
    name: oidcProvider
    base:
      apiVersion: iam.aws.upbound.io/v1beta1
      kind: OpenIDConnectProvider
      spec:
        forProvider:
          clientIDList:
            - sts.amazonaws.com
          thumbprintList:
            - "9e99a48a9960b14926bb7f3b02e22da2b0ab7280"
    patches:
      - fromFieldPath: status.eks.oidc
        toFieldPath: spec.forProvider.url
        policy:
          fromFieldPath: Required