apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: upbound-demo
spec:
  crossplane:
    version: ">=v1.9.0-0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-aws
      version: ">=v0.18.0"
