- op: add
  path: /spec/resources/-
  value:
    name: routeTable
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: RouteTable
    patches:
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.vpcIdSelector.matchLabels[vpc]
        transforms:
          - type: string
            string:
              fmt: "%s-vpc"
      - fromFieldPath: spec.region
        toFieldPath: spec.forProvider.region
      - type: PatchSet
        patchSetName: network-id
      - fromFieldPath: spec.id
        toFieldPath: metadata.name
        transforms:
        - type: string
          string:
            fmt: "%s-rttbl"
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.tags.name
- op: add
  path: /spec/resources/-
  value:
    name: RouteTableAssociationA
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: RouteTableAssociation
      spec:
        forProvider:
          subnetIdSelector:
            matchControllerRef: true
            matchLabels:
              access: private
    patches:
      - type: PatchSet
        patchSetName: network-id
      - fromFieldPath: spec.region
        toFieldPath: spec.forProvider.region
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.routeTableIdRef.name
        transforms:
        - type: string
          string:
            fmt: "%s-rttbl"
      - fromFieldPath: spec.region
        toFieldPath: spec.forProvider.subnetIdSelector.matchLabels[zone]
        transforms:
          - type: string
            string:
              fmt: "%sa"
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.tags.name
      - fromFieldPath: spec.id
        toFieldPath: metadata.name
        transforms:
        - type: string
          string:
            fmt: "%s-rta-a"
- op: add
  path: /spec/resources/-
  value:
    name: RouteTableAssociationB
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: RouteTableAssociation
      spec:
        forProvider:
          subnetIdSelector:
            matchControllerRef: true
            matchLabels:
              access: private
    patches:
      - type: PatchSet
        patchSetName: network-id
      - fromFieldPath: spec.region
        toFieldPath: spec.forProvider.region
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.routeTableIdRef.name
        transforms:
          - type: string
            string:
              fmt: "%s-rttbl"
      - fromFieldPath: spec.region
        toFieldPath: spec.forProvider.subnetIdSelector.matchLabels[zone]
        transforms:
          - type: string
            string:
              fmt: "%sb"
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.tags.name
      - fromFieldPath: spec.id
        toFieldPath: metadata.name
        transforms:
          - type: string
            string:
              fmt: "%s-rta-b"