- op: add
  path: /spec/resources/-
  value:
    name: subnet-private-a
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: Subnet
      metadata:
        labels:
          access: private
      spec:
        forProvider:
          cidrBlock: 192.168.0.0/18
          vpcIdSelector:
            matchControllerRef: true
          tags:
            kubernetes.io/role/internal-elb: "1"
    patches:
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.vpcIdSelector.matchLabels[vpc]
        transforms:
          - type: string
            string:
              fmt: "%s-vpc"
      - fromFieldPath: spec.region
        toFieldPath: spec.forProvider.availabilityZone
        transforms:
          - type: string
            string:
              fmt: "%sa"
      - fromFieldPath: spec.region
        toFieldPath: metadata.labels[zone]
        transforms:
          - type: string
            string:
              fmt: "%sa"
      - fromFieldPath: spec.region
        toFieldPath: spec.forProvider.region
      - type: PatchSet
        patchSetName: network-id
- op: add
  path: /spec/resources/-
  value:
    name: subnet-private-b
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: Subnet
      metadata:
        labels:
          access: private
      spec:
        forProvider:
          cidrBlock: 192.168.64.0/18
          vpcIdSelector:
            matchControllerRef: true
          tags:
            kubernetes.io/role/elb: "1"
    patches:
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.vpcIdSelector.matchLabels[vpc]
        transforms:
          - type: string
            string:
              fmt: "%s-vpc"
      - fromFieldPath: spec.region
        toFieldPath: spec.forProvider.availabilityZone
        transforms:
          - type: string
            string:
              fmt: "%sb"
      - fromFieldPath: spec.region
        toFieldPath: metadata.labels[zone]
        transforms:
          - type: string
            string:
              fmt: "%sb"
      - fromFieldPath: spec.region
        toFieldPath: spec.forProvider.region
      - type: PatchSet
        patchSetName: network-id